[general]
import = [
"~/.config/alacritty/themes/monokai_pro.toml"
]

[window]
decorations = "None"
opacity = 0.9
startup_mode = "Maximized"
padding = { x = 10, y = 0 }

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12
offset = { x = 0, y = 1 }
glyph_offset = { x = 1, y = 1 }
