shell=/bin/bash

font=MononokiNerdFont:size=12
pad=10x5x10x5

[colors-dark]
background=2d2a2e
alpha=0.85

# black
regular0=2d2a2e
# red
regular1=ff6188
# green
regular2=a9dc76
# yellow
regular3=ffd866
# blue
regular4=78dce8
# Magenta
regular5=ff6188
# Cyan
regular6=78dce8
# white
regular7=fff1f3

