#!/usr/bin/env bash

while :; do
    count=$(xbps-install --memory-sync --dry-run --update 2>/dev/null | grep -E 'update|install' | wc -l)
    echo "$count" > /tmp/pkgs-updates-count
    sleep 3600
done
