#!/usr/bin/env bash

# set PATH so it includes user's private bin if it exists
if $(echo $PATH | grep -v "$HOME/bin" &>/dev/null); then
    if [ -d "$HOME/bin" ] ; then
        PATH="$HOME/bin:$PATH"
    fi
fi

# set PATH so it includes user's private bin if it exists
if $(echo $PATH | grep -v "$HOME/.local/bin" &>/dev/null); then
    if [ -d "$HOME/.local/bin" ] ; then
        PATH="$HOME/.local/bin:$PATH"
    fi
fi

# set default editor
EDITOR=vi

