#!/usr/bin/env bash

BOLD='\[\e[1m\]'

BLACK='\[\e[30m\]'
RED='\[\e[31m\]'
GREEN='\[\e[32m\]'
YELLOW='\[\e[33m\]'
BLUE='\[\e[34m\]'
MAGENTA='\[\e[35m\]'
CYAN='\[\e[36m\]'
WHITE='\[\e[37m\]'
RESET='\[\e[0m\]'

pink() {
    echo "${RED}$1${RESET}"
}

yellow() {
    echo "${YELLOW}$1${RESET}"
}

cyan() {
    echo "${CYAN}$1${RESET}"
}

green() {
    echo "${GREEN}$1${RESET}"
}

short_pwd() {
    [[ "$PWD" == "$HOME" ]] && echo "~" || basename "$PWD"
}

parse_git_branch() {
    git rev-parse --is-inside-work-tree &>/dev/null || return

    local branch
    branch=$(git symbolic-ref --short HEAD 2>/dev/null || git describe --tags --exact-match 2>/dev/null)

    local status
    if [[ -n $(git status --porcelain 2>/dev/null) ]]; then
        status="[+]"
    else
        status=""
    fi

    echo "${branch} ${status}"
}

build_prompt() {
    local user="$(green "\u")"
    local path="$(green "  \w")"

    local git_branch=$(parse_git_branch)
    local gitinfo=""
    if [ -n "$git_branch" ]; then
        local gitinfo="$(pink " $git_branch")"
    fi

    local prompt="$(green "")"
    
    PS1="\n${path}  ${gitinfo}\n${prompt} "
}

build_tty_prompt() {
    local user="${BOLD}$(green "\u")"
    local path="$(green "\w")"
    local gitinfo="$(pink "$(parse_git_branch)")"
    local prompt="$(green "\$")"
    
    PS1="\n${path}  ${gitinfo}\n${prompt} "
}

IS_TTY=$(tty | grep tty)

if [ -z "$IS_TTY" ]; then
    PROMPT_COMMAND=build_prompt
else
    PROMPT_COMMAND=build_tty_prompt
fi
