# Default colors
[colors.primary]
background = '#2D2A2E'
foreground = '#fff1f3'

# Normal colors
[colors.normal]
black   = '#2c2525'
red     = '#ff6188'
green   = '#a9dc76'
yellow  = '#ffd866'
blue    = '#a8a9eb'
magenta = '#ff6188'
cyan    = '#78dce8'
white   = '#fff1f3'

# Bright colors
[colors.bright]
black   = '#72696a'
red     = '#ff6188'
green   = '#a9dc76'
yellow  = '#ffd866'
blue    = '#a8a9eb'
magenta = '#ff6188'
cyan    = '#78dce8'
white   = '#fff1f3'
